tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/brewdler'
tap 'homebrew/bundle'
tap 'homebrew/python'
tap 'homebrew/science'
tap 'homebrew/versions'
tap 'rcmdnk/file'
tap 'sanemat/font'
cask 'java'
cask 'xquartz'
brew 'ant'
brew 'autoconf'
brew 'xz'
brew 'automake'
brew 'binutils'
brew 'icu4c'
brew 'boost'
brew 'ghc'
brew 'cabal-install'
brew 'cabextract'
brew 'pkg-config'
brew 'libpng', args: ['universal']
brew 'freetype', args: ['universal']
brew 'fontconfig', args: ['universal']
brew 'pixman'
brew 'gettext'
brew 'libffi'
brew 'glib'
brew 'cairo'
brew 'libtasn1', args: ['universal']
brew 'gmp'
brew 'nettle'
brew 'gnutls'
brew 'emacs', args: ['with-cocoa']
brew 'cask'
brew 'isl'
brew 'cloog'
brew 'cmake'
brew 'nkf'
brew 'cmigemo'
brew 'coreutils'
brew 'libsodium'
brew 'zeromq'
brew 'czmq'
brew 'dmd'
brew 'eigen'
brew 'pcre'
brew 'git'
brew 'x264'
brew 'lame'
brew 'libvo-aacenc'
brew 'xvid'
brew 'makedepend'
brew 'openssl', args: ['universal']
brew 'ffmpeg'
brew 'libtool', args: ['universal']
brew 'gobject-introspection'
brew 'harfbuzz'
brew 'pango'
brew 'jpeg', args: ['universal']
brew 'libtiff', args: ['universal']
brew 'fontforge'
brew 'mpfr'
brew 'libmpc'
brew 'gcc'
brew 'gd', args: ['universal']
brew 'gdbm'
brew 'lua'
brew 'readline'
brew 'qt'
brew 'gnuplot'
brew 'ilmbase'
brew 'jasper', args: ['universal']
brew 'jbig2dec'
brew 'libevent'
brew 'libusb', args: ['universal']
brew 'libusb-compat', args: ['universal']
brew 'libgphoto2', args: ['universal']
brew 'libicns', args: ['universal']
brew 'sqlite'
brew 'python'
brew 'libxml2'
brew 'little-cms', args: ['universal']
brew 'little-cms2', args: ['universal']
brew 'llvm', args: ['with-clang', 'universal', 'with-rtti']
brew 'openexr'
brew 'ossp-uuid'
brew 'p7zip'
brew 'ruby-build', args: ['HEAD']
brew 'rbenv'
brew 'rename'
brew 'sane-backends', args: ['universal']
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'watch'
brew 'wget'
brew 'wine'
brew 'winetricks'
brew 'zsh'
brew 'zsh-completions'
brew 'caskroom/cask/brew-cask'
brew 'homebrew/python/numpy'
brew 'homebrew/science/glpk'
brew 'homebrew/science/opencv3'
brew 'homebrew/science/r'
brew 'homebrew/versions/gmp4'
brew 'homebrew/versions/isl011'
brew 'homebrew/versions/cloog018'
brew 'homebrew/versions/mpfr2'
brew 'homebrew/versions/libmpc08'
brew 'homebrew/versions/gcc48'
brew 'sanemat/font/ricty'
cask 'adobe-reader'
cask 'cheatsheet'
cask 'dropbox'
cask 'eclipse-java'
cask 'evernote'
cask 'google-chrome'
cask 'google-drive'
cask 'google-japanese-ime'
cask 'iterm2'
cask 'karabiner'
cask 'seil'
cask 'skype'
cask 'sublime-text'
cask 'teamviewer'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
