[tools]
python = "latest"
node = "latest"
go = "latest"
rust = "latest"
ruby = "latest"
jq = "latest"
peco = "latest"
awscli = "latest"
aws-sam-cli = "latest"
poetry = "latest"
pipenv = "latest"
pipx = "latest"
upx = "latest"
