[tools]
actionlint = "latest"
aws-cli = "latest"
aws-sam = "latest"
aws-vault = "latest"
gh = "latest"
gitleaks = "latest"
go = "latest"
jq = "latest"
nerdctl = "latest"
node = "24"
peco = "0.5.11" # 0.6.0 installation is broken
pipx = "latest"
"pipx:pipenv" = "latest"
pnpm = "latest"
poetry = "latest"
python = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
upx = "latest"
usage = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = []
