# Defines environment variables and XDG Base Directories

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

# Pivot zsh configurations into XDG_CONFIG_HOME
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "$ZDOTDIR/.zprofile" ]]; then
  source "$ZDOTDIR/.zprofile"
fi

if [ -e $HOME/.cargo/env ]; then
  . "$HOME/.cargo/env"
fi
